Register nickname script and ts debug configuration
peeramid-labs/multipass pull request #20
Opened 2024-11-10 15:52 UTC by theKosmoss

2024-11-10 15:53 UTC, theKosmoss commented on scripts/register.ts
> +        const tx = await contract.register(
This works

2024-11-13 10:40 UTC, peersky requested changes
some changes desired

2024-11-13 10:40 UTC, peersky commented on .vscode/launch.json
Please don't commit .vscode files. We should keep our work IDE agnostic.

2024-11-13 10:40 UTC, peersky commented on playbook/utils/deploy-to-local-anvil.sh
> +rm -rf ./artifacts
I would also suggest removing `./cache`

2024-11-13 10:40 UTC, peersky commented on scripts/register.ts
> +            { maxFeePerGas: 100000000000, maxPriorityFeePerGas: 1000000000, value: 0 }
Can we remove `maxFeePerGas` and `maxPriorityFeePerGas` ? I think they got here as debug values, we should not need them really.

2024-11-13 10:42 UTC, peersky commented
also needs changeset

2024-12-03 09:50 UTC, peersky approved these changes
looks good, just optimize imports a bit

2024-12-03 09:50 UTC, peersky commented on playbook/initializeDomain.ts
> +import { ethers } from 'ethers';
I suggest using hre.ethers instead

2024-12-03 09:50 UTC, peersky commented on playbook/initializeDomain.ts
> +          validUntil: ethers.BigNumber.from(Math.floor(Date.now() / 1000) + (365 * 24 * 60 * 60)),
use hre.ethers instead

2024-12-03 09:50 UTC, peersky commented on playbook/initializeDomain.ts
> +          validUntil: ethers.BigNumber.from(Math.floor(Date.now() / 1000) + (365 * 24 * 60 * 60)),
```suggestion
          validUntil: hre.ethers.BigNumber.from(Math.floor(Date.now() / 1000) + (365 * 24 * 60 * 60)),
```

2024-12-03 09:50 UTC, peersky commented on playbook/initializeDomain.ts
> +import { ethers } from 'ethers';
```suggestion
```

2024-12-03 10:13 UTC, merged